type: 'yolox'
params:
  accelerator: cuda:0
  conf: 0.6
  min_bbox_area: 100
  model_path: /media/home/DanceTrack-orig/.other/bytetrack_models/bytetrack_model.pth.tar
lookup_path: /media/home/DanceTrack-orig/.other/.lookup.json
oracle: true