defaults:
  - global_config
  - dataset: dancetrack.yaml
  - inference: val.yaml
  - eval: default.yaml
  - object_detection: mmdet_yolox_dancetrack.yaml
  - algorithm: movesort.yaml
  - postprocess: dancetrack.yaml
  - path: default.yaml
  - _self_


experiment: 'movesort'
