inference:
  postprocess: true

eval:
  eval_output: 'offline'

optimizer:
  n_trials: 100
  sampler: tpe
  sampler_params: {}
  direction: maximize
  search_space:

    # --- Object detection ---
    algorithm.params.detection_threshold:
      type: float
      low: 0.1
      high: 0.9

    # --- Algorithm: Core tracking params ---
    algorithm.params.initialization_threshold:
      type: int
      low: 0
      high: 3
    algorithm.params.remember_threshold:
      type: int
      low: 1
      high: 60

    # --- Algorithm: Filter (motion model) params ---
    algorithm.params.filter.params.override_std_weight_position:
      type: float
      low: 0.01
      high: 0.25
