defaults:
  - global_config
  - dataset: dancetrack.yaml
  - inference: val.yaml
  - eval: default.yaml
  - object_detection: mmdet_yolox_low_conf_dancetrack.yaml
  - algorithm: sparsetrack.yaml
  - postprocess: dancetrack.yaml
  - path: default.yaml
  - _self_


experiment: 'sparsetrack'
