defaults:
  - global_config
  - dataset: mot20.yaml
  - eval: val.yaml
  - object_detection: yolox_ablation_low_conf_mot20.yaml
  - algorithm: bytetrack.yaml
  - postprocess: default.yaml
  - path: default.yaml
  - _self_


experiment: 'mot20-bytetrack'
