defaults:
  - global_config
  - dataset: soccernet.yaml
  - eval: val.yaml
  - object_detection: yolox_low_conf_sportsmot.yaml
  - algorithm: botsort_reid.yaml
  - postprocess: soccernet.yaml
  - path: default.yaml
  - _self_

experiment: 'soccernet-botsort-reid'
