defaults:
  - global_config
  - dataset: soccernet.yaml
  - eval: val.yaml
  - object_detection: yolov8_low_conf_soccernet.yaml
  - algorithm: sort.yaml
  - postprocess: soccernet.yaml
  - path: default.yaml
  - _self_

experiment: 'soccernet-sort'
