name: byte
params:
  filter:
    name: bot-sort
    params:
      override_std_weight_position: 0.05
  initialization_threshold: 3
  new_tracklet_detection_threshold: 0.7
  remember_threshold: 30
  detection_threshold: 0.6
  high_matcher:
    name: compose
    params:
      matchers:
        - name: iou
          params:
           match_threshold: 0.25
        - name: distance
          params:
            distance_name: l1
        - name: hybrid-conf
          params: {}
      weights:
        - 1
        - 5
        - 4
  low_matcher:
    name: compose
    params:
      matchers:
        - name: iou
          params:
           match_threshold: 0.5
        - name: distance
          params:
            distance_name: l1
        - name: hybrid-conf
          params: {}
      weights:
        - 1
        - 5
        - 2
  new_matcher:
    name: iou
    params:
      match_threshold: 0.25