name: byte
params:
  filter_name: bot-sort
  filter_params:
    override_std_weight_position: 0.05
  initialization_threshold: 3
  new_tracklet_detection_threshold: 0.7
  remember_threshold: 30
  detection_threshold: 0.6
  high_matcher_algorithm: iou
  high_matcher_params:
    match_threshold: 0.25
  low_matcher_algorithm: iou
  low_matcher_params:
    match_threshold: 0.50
  new_matcher_algorithm: iou
  new_matcher_params:
    match_threshold: 0.25