name: sort
params:
  filter_name: bot-sort
  filter_params:
    override_std_weight_position: 0.01
  initialization_threshold: 3
  remember_threshold: 30
  matcher_algorithm: reid-iou
  matcher_params:
    match_threshold: 0.2
    appearance_weight: 0.50
    appearance_threshold: 0.00
    appearance_metric: 'cosine'
    appearance_ema_momentum: 0.95

  # ReID extension
  reid_name: fastreid-onnx
  reid_params:
    model_path: /media/home/reid/SBS.onnx
    height: 384
    width: 128
    cache_path: /tmp/reid_sbs50  # Cache inference for faster future runs (should be deleted if the detector changed)

requires_image: true