# SparseTrack = ByteTrack + DCM
name: sparse
params:
  filter_name: bot-sort
  filter_params:
    override_std_weight_position: 0.05
  initialization_threshold: 3
  remember_threshold: 30
  new_tracklet_detection_threshold: 0.7
  detection_threshold: 0.6
  high_matcher_algorithm: dcm
  high_matcher_params:
    levels: 12
    match_threshold: 0.25
  low_matcher_algorithm: dcm
  low_matcher_params:
    levels: 12
    match_threshold: 0.50
  new_matcher_algorithm: iou
  new_matcher_params:
    match_threshold: 0.25