defaults:
  - global_config
  - dataset: mot17.yaml
  - eval: val.yaml
  - object_detection: yolox_ablation_low_conf_mot17.yaml
  - algorithm: bytetrack.yaml
  - postprocess: mot17.yaml
  - path: default.yaml
  - _self_


experiment: 'mot17-bytetrack'
