# Bot-Sort without ReID = ByteTrack + CMC
name: byte
params:
  filter_name: bot-sort
  filter_params:
    override_std_weight_position: 0.05
  initialization_threshold: 3
  remember_threshold: 30
  new_tracklet_detection_threshold: 0.7
  detection_threshold: 0.6
  high_matcher_algorithm: reid-iou-fusion
  high_matcher_params:
    match_threshold: 0.05
    appearance_weight: 0.7
    proximity_threshold: 0.5
  low_matcher_algorithm: iou
  low_matcher_params:
    match_threshold: 0.50
  new_matcher_algorithm: iou
  new_matcher_params:
    match_threshold: 0.25

  # CMC extension
  cmc_name: gmc-from-file
  cmc_params:
    dirpath: /media/home/GMC_files/DanceTrack

  reid_name: fastreid-onnx
  reid_params:
    model_path: /media/home/reid/SBS.onnx
    height: 384
    width: 128
    cache_path: /tmp/reid_sbs50  # Cache inference for faster future runs (should be deleted if the detector changed)
    batch_inference: False