name: sort
params:
  filter_name: bot-sort
  filter_params:
    override_std_weight_position: 0.05
  initialization_threshold: 3
  matcher_algorithm: move
  matcher_params:
    distance_name: l1
    match_threshold: 0.2
    motion_lambda: 5
  remember_threshold: 30

  # MoveSORT-GMC extension
  cmc_name: gmc-from-file
  cmc_params:
    dirpath: /media/home/GMC_files/DanceTrack

requires_image: true