defaults:
  - global_config
  - dataset: dancetrack.yaml
  - eval: val.yaml
  - object_detection: yolox_dancetrack.yaml
  - algorithm: movesort_gmc.yaml
  - path: default.yaml
  - _self_


experiment: 'movesort_with_gmc'
