defaults:
  - global_config
  - dataset: dancetrack.yaml
  - eval: val.yaml
  - object_detection: yolox_dancetrack.yaml
  - algorithm: reid_sort.yaml
  - postprocess: dancetrack.yaml
  - path: default.yaml
  - _self_


experiment: 'sort-reid'
