# Bot-Sort without ReID = ByteTrack + CMC
name: byte
params:
  filter:
    name: bot-sort
    params:
      override_std_weight_position: 0.05
  initialization_threshold: 3
  remember_threshold: 30
  new_tracklet_detection_threshold: 0.7
  detection_threshold: 0.6
  high_matcher:
    name: iou
    params:
      match_threshold: 0.25
  low_matcher:
    name: iou
    params:
      match_threshold: 0.50
  new_matcher:
    name: iou
    params:
      match_threshold: 0.25

  # CMC extension
  cmc:
    name: gmc-from-file
    params:
      dirpath: /media/home/GMC_files/DanceTrack