"""
Conventions formats.
"""
DATE_FORMAT = '%Y-%m-%d'
TIME_FORMAT_SHORT = '%H-%M-%S'
TIME_FORMAT = '%H-%M-%S.%f'
RUN_DATETIME_FORMAT = f'{DATE_FORMAT}_{TIME_FORMAT_SHORT}'
DATETIME_FORMAT = f'{DATE_FORMAT}_{TIME_FORMAT}'
