type: 'yolox'
params:
  accelerator: cuda:0
  conf: 0.1
  min_bbox_area: 100
  # Model source: https://github.com/ifzhang/ByteTrack, ByteTrack_ablation
  model_path: /media/home/models/detection/sportsmot.pth.tar
lookup_path: /media/home/models/detection/sportsmot.lookup.json
oracle: false
cache_path: '/workspace/motrack/sportsmot_yolox_low_conf'  # Inference on the second run is 10-20 times faster